/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary-base)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-active": "var(--color-primary-active)",
        default: "var(--color-text)",
        "default-background": "var(--color-fill-content)",
        secondary: "var(--color-text-description)",
        "secondary-foreground": "var(--color-text)",
        muted: "var(--color-bg-container-disabled)",
        "muted-foreground": "var(--color-text-disabled)",
        border: "var(--color-border)",
        background: "var(--color-bg-container)",
        foreground: "var(--color-text)",
        destructive: "var(--color-error-base)",
        "hover-input-primary": "var(--color-primary-border-hover)",
        positive: "var(--color-success-base)",
        warning: "var(--color-warning-base)",
        "card-fill-tertiary": "var(--color-fill-tertiary)",
        "primary-10": "var(--color-primary-bg)",
        input: "var(--color-border)",
        popover: "var(--color-bg-container)",
        "popover-foreground": "var(--color-text)",
        "input-disabled-background": "var(--color-bg-container-disabled)",
        "spotlight-background": "var(--color-bg-spotlight)",
        "primary-foreground": "var(--color-text-light-solid)",
        "hover-background": "var(--color-fill-content-hover)",
        "border-primary": "var(--color-primary-border)",
        "border-tabs": "var(--color-border-secondary)",
        "switch-background": "var(--color-fill-content)",
        "banner-purple-bg": "var(--color-banner-purple-bg)",
        "banner-purple-fg": "var(--color-banner-purple-fg)",
        "banner-green-bg": "var(--color-banner-green-bg)",
        "banner-green-fg": "var(--color-banner-green-fg)",
        "banner-gold-bg": "var(--color-banner-gold-bg)",
        "banner-gold-fg": "var(--color-banner-gold-fg)",
        "banner-red-bg": "var(--color-banner-red-bg)",
        "banner-red-fg": "var(--color-banner-red-fg)",
      },
      boxShadow: {
        focus: "0 0 0 2px var(--control-outline)",
        error: "0px 0px 0px 2px var(--color-error-outline)",
      },
      fontFamily: {
        cofo: ["var(--font-cofo-mono)"],
        graphik: ["var(--font-graphik)"],
      },
    },
  },
  plugins: [],
};
